import Config

# Configure your database
config :task_forest, TaskForest.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "task_forest_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

enable_code_reloader = System.get_env("CODE_RELOADER_OFF") != "true"

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :task_forest, TaskForestWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: enable_code_reloader,
  debug_errors: true,
  secret_key_base: "aXh2gZDBaEqRadXLExBy7mivXE/iQefw8heW3XlUwbyV/ArAOKOBgfe5UkSVY4fG",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:task_forest, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:task_forest, ~w(--watch)]}
  ],
  live_reload: [
    notify: [
      live_view: [
        ~r"lib/task_forest_web/core_components.ex$",
        ~r"lib/task_forest_web/(live|components)/*/.*(ex|heex)$"
      ]
    ],
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/task_forest_web/controllers/.*(ex|heex)$",
      ~r"lib/task_forest_web/controllers/*/.*(ex|heex)$"
    ]
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :task_forest, TaskForestWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/task_forest_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :task_forest, dev_routes: true

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
